import '../styles/layout/Main.scss';
import PropTypes from 'prop-types';

const Keyboard = (props) => {
  return (
    <div className="keyboard">
      <div className="keyboard__row">
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'q'}
        >
          q
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'w'}
        >
          w
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'e'}
        >
          e
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'r'}
        >
          r
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'t'}
        >
          t
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'y'}
        >
          y
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'u'}
        >
          u
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'i'}
        >
          i
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'o'}
        >
          o
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'p'}
        >
          p
        </button>
      </div>
      <div className="keyboard__row">
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'a'}
        >
          a
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'s'}
        >
          s
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'d'}
        >
          d
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'f'}
        >
          f
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'g'}
        >
          g
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'h'}
        >
          h
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'j'}
        >
          j
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'k'}
        >
          k
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'l'}
        >
          l
        </button>
      </div>
      <div className="keyboard__row">
        <button onSubmit={props.handleEnter} className="keyboard__key">
          Enter
        </button>
        {/* ATTENTION: Enter should be onSummit */}
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'z'}
        >
          z
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'x'}
        >
          x
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'c'}
        >
          c
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'v'}
        >
          v
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'b'}
        >
          b
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'n'}
        >
          n
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'m'}
        >
          m
        </button>
        <button
          onClick={props.handleClick}
          className="keyboard__key"
          value={'Del'}
        >
          Del
        </button>
      </div>
    </div>
  );
};

export default Keyboard;

Keyboard.propTypes = {
  handleClick: PropTypes.func,
  handleEnter: PropTypes.func,
};
